### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by thomas-enxuli** [robot-learning-freiburg/EfficientLPS#1]
Hi there, I read the paper and it was very impressive and interesting work. Just wondering is there any plan on releasing the code? Thanks.

**Comment by avalada** [comment]
Thanks! We plan to release the code once we receive the decision on the paper from the journal. We just submitted it to review so it would probably take a few months. Stay tuned!

**Comment by thomas-enxuli** [comment]
Thanks! Closing the issue.

**Comment by gujiaqivadin** [comment]
Hello @avalada , how is it going with your paper submitting? I am new to panoptic segmentation of point cloud area and looking forward to your excellent paper with code releasing.

**Comment by owoshch** [comment]
Hi @avalada. Thank you for the excellent work. I wondered if you could guide us on the expected timeline of posting the code to reproduce your results. Thank you!

**Comment by avalada** [comment]
Thank you all for your interest in our work. We are in the rebuttal stage and we expect to release the code in about 2 months.

**Comment by davodogster** [comment]
@avalada Hi is the code available now?
Cheers, Sam

**Comment by lfxx** [comment]
> We will release it by the end of Sep

any update?

**Comment by sundermann** [comment]
Any updates?

**Comment by davodogster** [comment]
@avalada  Hi any update?

**Comment by avalada** [comment]
Thanks for the patience. The code will be pushed by the end of this month!

**Comment by sundermann** [comment]
Any update on the code release?

**Comment by mohan1914** [comment]
The code is online now.
