### ISSUE TITLE
How can I visualize predictions' point cloud view

### ISSUE THREAD

**Issue by gunjupark** [robot-learning-freiburg/EfficientLPS#11]
Hello 

I want to see results's 3D Point cloud view (back projected).

How can I see them.

**Comment by LiXiang0021** [comment]
Have you slove this issue?

**Comment by gunjupark** [comment]
> Have you slove this issue?

yes. you can extract results in code.

maybe variable name is pred_~~~ and make that numpy array's format to semantic kitti's label format.

and using semantic kitti api's visualize
