### ISSUE TITLE
Scan and label don't contain same number of points in NuScenes dataset

### ISSUE THREAD

**Issue by venture2928** [robot-learning-freiburg/EfficientLPS#2]
Hi there, I read your paper and tried the NuScenes LiDAR Panoptic Segmentation Dataset on your homepage, after run the file 'nuscenes_to_kitti_data_converter.py', scan and label don't contain same number of points. I am wondering is there a file matching problem or a conversion error? Thanks a lot.

**Comment by mohan1914** [comment]
There is an official [Panoptic nuScenes](https://www.nuscenes.org/) dataset that we generated and is available for download. It shouldn't have any problems.
